---
title: "augmente-intelligence"
author: "J. Adrián Sánchez"
date: "2/5/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Three days a er removing human editors, Facebook is already trending fake news, August 26,2016


- At facebook humans would no longer write descriptions for its Trending topics list (small editorial team to write descriptions for each trending topic), handing over an algorithm.

- Instead of relying on an automatically selected article, Facebook used to employ a small editorial team to write descriptions for each trending topic. The team that suggested (among many other things) that the Trending list was “biased” against conservative topics and news sources.

- The algorithm considers a combination of volume (spikes) and momentum (lot of original mentions)

- Facebook’s algorithm chose a very bad, factually incorrect headline to explain to its news-hungry users why Megyn Kelly was trending.

-Headlines like the one about Kelly are designed to be shared and believed by those who are already inclined to share and believe them. And they do.

##Discussion
1. White's bias in algorithms?
2. Perfect algorithm? what is perfect?
3. Agenda Setting? Journalist setting?
4. Audience degree of belief

### The Chess Master and the Computer, February 11, 2010

- The lost of Kasparov against DeepBlue symbol of mankind’s submission before the almighty computer.

- They got one that played like a machine, systematically evaluating 200 million possible moves on the chess board per second and winning with **brute number-crunching force**.

- No one understood all the ramifications of having a super-grandmaster on your laptop -> **Digital Inclusion vs Digital Divide.**

- Some replied to this with variations on the theme of how we still hold footraces despite cars and bicycles going much faster, a spurious analogy since cars do not help humans run faster while chess **computers undoubtedly have an effect on the quality of human chess.**

- Today’s teens, and increasingly pre-teens, **can accelerate this process by plugging into a digitized** archive of chess information and making full use of the **superiority of the young mind to retain it all.** -> DEvelopment envirenment

- Where art and science come together in the humanmind and are then refined and **improved by experience**.-> Can computer have this also?

- **Computers are good at is where humans are weak, and vice versa** -> A synthesis of the best of man and machine.-> **We could concentrate on strategic planning** instead of spending so much time on calculations.

- ** Weak human + machine + better process**

- There is little doubt that different people are blessed with different amounts of **cognitive gifts**.-> The ability to **work hard for days on end without losing focus is a talent**. The ability to keep absorbing new information after many hours of study is a talent.



### Digital Ubiquity, November 2014

-new eficiencies and other benefits through advanced analytics and algorithms based on the data generated by that equipment.-> **Industrial Internet**-> on the newfound **ubiquity of digital connectivity.**

-  computing power is available at very **low cost through cloud computing** -> deployment of digital sensors is **extending digitization and connectivity** to previously analog tasks.

- **Digital transformation**—the digitization of previously analog machine and service operations, organizational tasks, and managerial processes—is pushing both established and start‐up players in many industries **to compete in new ways**. -> To compete, companies will have to **rethink their business models**, identifying new opportunities for creating and capturing value.

- **Digital transformation** changes how the organization creates value for its customers (the cus- tomer value proposition) and how it captures that value (how it makes money). ->The potential for new applications and services is astonishing.

- Initiatives such as the GE proposes an **open global network of machines, data, and people** to generate a plethora of **new business** opportunities and outcomes-based business models. -> Itunes/Appstore Marketplace.

- Rapid cross-industry innovation. It would also enable independent developers to build applications on GE’s platform. -> How is this different from Open Government?

- A new way of thinking abut product management, marketing, sales and commercial operations, delivery. -> New partnerships ->to truly understand our customers’ business and  nancial situation, how they make money. 

- **Building out the ecosystem**.  They needed to strengthen the loose **network of suppliers, distributors, and developers** of related products and services that enable and enhance offerings. -> We **partner with competitors.**

- More on crowdsourcing for in- novation.

- Examine **new modes of value creation** -> **What new data could you accumulate?**

- Invest in software-related skills that complement.


### Winning the Race With Ever-Smarter Machines, Winter 2012

- Pattern recognition tasks where the rules can’t be inferred.? ->Can Machines learn? Alan Turing
**Examples:** Self-driving cars, Apple's Siri personal assistant, Jeopardy

- Moore's Law? Decay? - Jumping technology? GPU's?

- Cheap computers and telecommunications equipment can foster an everexpanding sequence of complementary inventions in industries using ICT.

-  Over time, **technological progress creates opportunities in which people race using machines.** -> Digital Divide??

-  The key to winning the race is not to race against machines, but to **win using machines**.

- How can we implement winning **“human + machine” strategies?** The solution is **organizational innovation:** inventing **new organizational structures, processes and business models** that leverage ever-advancing technology and human skills.

1. Create processes that combine the speed of technology with human insight.
2. Let humans be creative — and use technol- ogytotesttheirideas.
3. Leverage IT to enable new forms of human col- laboration and commerce.
4. Use human insight to apply IT — and IT-gen- erated data — to create more effective processes.


Because the **process of innovation** often **relies heavily** on combining and recombining **previous innovations,** the **broader and deeper the pool of accessible ideas and individuals,** the more opportunities there are for innovation. -> Social Physics




###Netflix Case

- Customer Churn Problem -> Not renewing subscriptions->Cinematch Algorithm increase its **accuracy in recommending** the right movies to the right people. -> After time they were unable to make significant improvements to the algorithm.-> run a prize-based contest and see what solutions came from the **“wisdom of the crowd.”**

- **Original business model** ->subscription service in October 1999 -> Customers created an online queue, or wish list, of the titles they wanted to rent and a title was sent to them based on an algorithm that accounted for demand and availability of that title.

- **Free trial** and marketing strategy as **"unlimited"**

- **Allocation** ->getting the right amount of product in the right locations. - > 2001, Netflix improved its distribution system.

- **Delivery time** was a key measure of customer **satisfaction for Netflix** and it continuously sought to improve the efficiency of its distribution centers


-  We needed to **stimulate demand on the older** and less known movies and things already in our catalog. ->first mover by **patenting** all novel aspects of its model. 

- faced challenges created by some of its own customers who could not resist **hacking into its system**.

-  80% of Netflix’s rental activity came from **2,000 titles** ->Inventory

- **Cinematch** was launched in February 2002 and was based on a Collaborative Filtering System (CFS). CFS predicted a customer’s taste by comparing the customer’s past preferences to those of people with similar tastes.-> Item based->  Were difficult to scale and also required a significant volume of ratings. 

- Estimates indicated that **60% of Netflix rentals were recommended by Cinematch** and in 2006 less than 30% of Netflix’s total rentals were new releases. 

- that recommendation systems were extremely hard to improve on -> **problem to accuracy**

-  we look at correlations between ratings, and that’s a **linear model**. Not all knowledge can be represented by a linear combination of features. This particular model... uses a nonlinear approach. I think that technique could be quite good.”

- Improving Cinematch through **Crowdsourcing**-> When you’re banging heads together in an office trying to come up with new ideas, you sometimes run out of ideas-> Creating a Community

- **Determining the Right Contest Strategy** -> inhouse-> **control over process, minimize exposure of data, investment**

- Could Hastings be absolutely sure that the viewing habits revealed in the data sets could not be **traced back to specific users?**

- issue of **intellectual property rights.**->  we don’t want to impede the winner’s ability to capitalize on it as well. 

- **Level of collaboration** ->  a problem with a problem that was too “big picture,” did not establish **clear technical specifications** for a viable submission, or had not been explained in an accessible way would likely end up with **solutions that were too abstract, expensive, complex, or incompatible to be realistically implemented by the company.**


- A qualifying test set containing more than 2.8 million customer/movie id pairs with rating dates, but no ratings. 



### Write-up
The early adoption (2002) of their digital capabilities and exploitation of data combined with a mindset of intellectual property rights protection, gave Netflix’s a first-mover advantage to innovate and become the leader in the industry. Non-only Netflix was able to use Operational Data but was able to connect all the information that was possible to collect. As the “Digital Ubiquity” article states, is that the new global economy will rely on companies that are able to “rethink their business models, identifying new opportunities for creating and capturing value”, and the way to go are the new modes of value creation, based in new data that organizations can accumulate. They not just used the information (data) from the traditional perspective of analyzing segments of the operations data, but were able to accumulate data from each part the customer experience and connect in a optimum “network”  database.

The keystone from my point of view is this mindset of thinking in “learning from the masses”. It reminded me about the research from Alex Pentland’s Social Physics concept of social learning: how human behavior is driven by the exchange of ideas –how people cooperate to discover, select and learn strategies and coordinate their actions.  Netflix, knew that as company have limited resources, the develop of their source of comparative advantage needed to develop further, therefore, there was a need to change, despite the risks that might encounter. The idea to open to a crowdsourcing mindset would require consideration of many possible outcomes and implications such as: intellectual property, incentives of participation and cooperation, infrastructure investment, integration of solutions, leakage of information to competitors, etc. Everything with the sole objective to optimizing the maximum percentage of possible solution space. 

Technological development is a source of amplifying the limits of what humans can understand and develop. Many of the social economist imply that development must be assure by the “right” incentives, specially those seen as a non-zero sum game of cooperation and participation. From my point of view, this kind of challenges gives this kind of “ecosystem” that create the perfect environment to give people the capacity to cooperate to discover, select and learn strategies and coordinate their actions. And the spillovers of this could impact the well-being of society. On the other hand, the question is about how to maximize well-being taking into account ethics and the respect of freedom of information and data protection rights.  Netflix, should launch another challenge that can combine all this constraints, with the only reasons that we as a humans can develop further. 
